# Generated by Django 4.2.7 on 2025-09-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content_type', models.CharField(choices=[('link', 'Link'), ('image', 'Image'), ('video', 'Video')], max_length=20, verbose_name='Content Type')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('file', models.FileField(blank=True, null=True, upload_to='content/', verbose_name='File')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in seconds', verbose_name='Duration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='agencies.agency', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-created_at'],
            },
        ),
    ]
