# Generated by Django 4.2.7 on 2025-09-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('days_of_week', models.JSONField(default=list, help_text='List of days (0=Monday, 6=Sunday)', verbose_name='Days of Week')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher number = higher priority', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content.content', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-priority', 'start_time'],
            },
        ),
    ]
